version: '3'

x-build: &default-build
  context: .
  dockerfile: Dockerfile

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=contact_book
      - POSTGRES_USER=contact_book_user
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: *default-build
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: [ "./scripts/start.sh" ]

volumes:
  contact_book:
