# Generated by Django 3.2.23 on 2023-11-07 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModelInformations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('basemodelinformations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.basemodelinformations')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('contacts.basemodelinformations',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('basemodelinformations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.basemodelinformations')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('status', models.CharField(default='Ativo', max_length=20, verbose_name=[('Ativo', 'Active'), ('Inativo', 'Inactive')])),
                ('favorite', models.BooleanField(default=False)),
                ('phone_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.phonetype')),
            ],
            bases=('contacts.basemodelinformations',),
        ),
    ]
