# Generated by Django 4.2.7 on 2023-11-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id_ref',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
