# Generated by Django 4.2.7 on 2023-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_user_id_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
